server:
  port: 8848
spring:
  application:
    name: World-City-Information
  jackson:
    default-property-inclusion: non-null
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      write-date-keys-as-timestamps: true
  redis:
    url: redis://localhost:6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/world?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  cache:
    type: redis
    redis:
      time-to-live:
        seconds: 2000
      cache-null-values: false
mybatis:
  type-aliases-package: example.world.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  file: log/${spring.application.name}.log
  level:
    example.world.mapper: debug